# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifter',
            name='bench',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lifter',
            name='clean_jerk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lifter',
            name='deadlift',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lifter',
            name='front_squat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lifter',
            name='push_press',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lifter',
            name='snatch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lifter',
            name='squat',
            field=models.IntegerField(null=True),
        ),
    ]
