# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('lift_type', models.CharField(choices=[('Powerlifting', (('Squat', 'Squat'), ('Bench', 'Bench'), ('Deadlift', 'Deadlift'))), ('Weightlifting', (('Snatch', 'Snatch'), ('Clean and Jerk', 'Clean and Jerk')))], max_length=50)),
                ('weight', models.IntegerField()),
                ('unit', models.CharField(choices=[('LB', 'pounds'), ('KG', 'kilograms')], max_length=2)),
                ('date_completed', models.DateField()),
                ('video_link', models.URLField()),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='people.Lifter')),
            ],
        ),
    ]
