# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_type', models.CharField(choices=[('Powerlifting', (('Squat', 'Squat'), ('Bench', 'Bench'), ('Deadlift', 'Deadlift'))), ('Olympic', (('Snatch', 'Snatch'), ('Clean and Jerk', 'Clean and Jerk'))), ('Misc', (('Strict Press', 'Strict Press'), ('Push Press', 'Push Press'), ('Front Squat', 'Front Squat')))], max_length=50)),
                ('weight', models.IntegerField()),
                ('unit', models.CharField(choices=[('LB', 'pounds'), ('KG', 'kilograms')], max_length=2)),
                ('reps', models.IntegerField()),
                ('date_completed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FederationRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.Record')),
                ('validated', models.BooleanField(default=False)),
                ('weight_class', models.IntegerField()),
                ('division', models.CharField(max_length=200)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Federation')),
            ],
            bases=('records.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='people.Gym'),
        ),
        migrations.AddField(
            model_name='record',
            name='lifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='people.Lifter'),
        ),
    ]
