# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('comments', models.TextField()),
                ('time_posted', models.DateTimeField()),
                ('post_title', models.CharField(max_length=200)),
                ('lift_type', models.CharField(choices=[('Powerlifting', (('Squat', 'Squat'), ('Bench', 'Bench'), ('Deadlift', 'Deadlift'))), ('Olympic', (('Snatch', 'Snatch'), ('Clean and Jerk', 'Clean and Jerk'))), ('Misc', (('Strict Press', 'Strict Press'), ('Push Press', 'Push Press'), ('Front Squat', 'Front Squat')))], max_length=50)),
                ('weight', models.IntegerField()),
                ('date_completed', models.DateField()),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Lifter')),
            ],
            options={
                'ordering': ('-time_posted',),
            },
        ),
    ]
