# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '__first__'),
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('video_link', models.URLField()),
                ('comments', models.TextField()),
                ('image_link', models.URLField()),
                ('time_posted', models.DateTimeField()),
                ('post_title', models.CharField(max_length=200)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Gym')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Lifter')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.Record')),
            ],
            options={
                'ordering': ('-time_posted',),
            },
        ),
    ]
