# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='people.Lifter'),
        ),
    ]
